### ISSUE TITLE
To few comments

### ISSUE THREAD

**Issue by ermini84** [fberke/YAIG#1]
Please insert more comments in your code!

@fberke @ermini84 

`<body class="logged-in env-production windows vis-public">
    

  <div class="position-relative js-header-wrapper ">
    <a href="#start-of-content" tabindex="1" class="accessibility-aid js-skip-to-content">Skip to content</a>
    <div id="js-pjax-loader-bar" class="pjax-loader-bar"><div class="progress" style="transition: width 0.4s ease 0s; width: 100%;"></div></div>
![c5lfxkvwaaae2a-](https://cloud.githubusercontent.com/assets/23113906/23264771/d769eabe-f9e2-11e6-906a-744ca453b24c.jpg)
`

**Comment by ermini84** [comment]
`<body class="logged-in env-production windows vis-public">
    

  <div class="position-relative js-header-wrapper ">
    <a href="#start-of-content" tabindex="1" class="accessibility-aid js-skip-to-content">Skip to content</a>
    <div id="js-pjax-loader-bar" class="pjax-loader-bar"><div class="progress" style="transition: width 0.4s ease 0s; width: 100%;"></div></div>`

**Comment by ermini84** [comment]
`<script></script>`

**Comment by ermini84** [comment]
![c5lfxkvwaaae2a-](https://cloud.githubusercontent.com/assets/23113906/23264948/67a972fc-f9e3-11e6-8de3-66b740c0bcb9.jpg)

**Comment by fberke** [comment]
This section is not for commenting, it's for posting issues.
Before posting code lines, please use the Preview function. If your code is rather long, or annyoing in other ways, please use gist.github.com
Closed.
